env: "local"

agent:
  name: ${AGENT_NAME}
  country: ${AGENT_COUNTRY}
  token: "${AGENT_TOKEN}"

kafka:
  brokers:
    - "91.107.126.43:9092"
  topics:
    tasks: "agent-tasks"
    results: "check-results" 
    logs: "agent-logs"

server:
  health_port: "8081"

backend:
  url: "0.0.0.0:8080"

checks:
  http_timeout: 10
  ping_timeout: 5
  tcp_timeout: 5
  dns_timeout: 5
